---

- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yml

  roles:
    - { role: common, tags: common }
    - { role: geerlingguy.ntp, tags: ntp }
    - { role: geerlingguy.firewall, tags: firewall }
    - { role: geerlingguy.repo-epel, tags: epel }
    - { role: geerlingguy.repo-remi, tags: remi }
    
    
