---

#All Servers
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml

  roles:
    - { role: geerlingguy.repo-epel, tags: epel }
    - { role: geerlingguy.repo-remi, tags: remi }
    - { role: common, tags: common }
    - { role: geerlingguy.ntp, tags: ntp }
    - { role: geerlingguy.firewall, tags: firewall }

#Applications
- hosts: apps
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml

  roles:
    - { role: geerlingguy.nginx, tags: nginx }
    - { role: geerlingguy.php, tags: php }
    - { role: geerlingguy.composer, tags: composer }


#Database
# - hosts: db
# become: yes
# gather_facts: yes

#Load Balancer
- hosts: lb
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml

  roles:
    - { role: haproxy, tags: haproxy }
